name: test-snap-lukewh-7
version: 0.0.3
summary: Just a test python snap
description: >
  Just a test python snap

confinement: classic
base: core22

parts:
  test-snap-lukewh:
    plugin: python
    python-version: python3
      source: .

apps:
  test-snap-lukewh:
    command: python3 test_snap.py
  test-snap-lukewh-7:
    command: python3 test_snap.py
